version: '3.7'

services:
  php-fpm:
    build: docker/php-fpm
    volumes:
      - ./:/var/www
    working_dir:
      /var/www
  builder:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: main
    working_dir: /app
    command:
      - composer install
    restart: 'no'