<?php

namespace App;

/**
 * Find the Difference
 *
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 *
 * Example 1:
 * Input: s = "abcd", t = "abcde"       Output: "e"         Explanation: 'e' is the letter that was added.
 *
 * Example 2:
 * Input: s = "", t = "y"               Output: "y"
 *
 * https://leetcode.com/problems/find-the-difference
 */
class FindDifference
{
    /**
     * @param string $s
     * @param string $t
     * @return string
     */
    public function findTheDifference(string $s, string $t): string
    {
        $sWords = str_split($s);
        $tWords = str_split($t);

        foreach ($sWords as $sWord) {
            foreach ($tWords as $index => $tWord) {
                if ($sWord === $tWord) {
                    unset($tWords[$index]);
                    break;
                }
            }
        }
        return implode('', $tWords);
    }
}
